### PR TITLE
Cache

### PR DESCRIPTION
**Pull request by Aprillion**
move background fetching for cache reload to browser

* CF workers kill hanging fetch requests, so previous version didn't run in production, only during local development
* fixing #106

Client code is getting more complex, but hopefully we can move the caching logic back to "server" in #94 if we start using HTTP streams...

### CODE REVIEW

**Comment by ccstan99** [comment]
I tested the changes for caching locally and everything looked great. However, when I deployed it to my test server, I just got header & footer with no content (empty list of questions), presumably because the already stored cache data format is different from what is now expected. After using "?reload" in the browser, I got: `TypeError: Cannot read properties of undefined (reading 'pageid')` Only the data for the key `initialQuestions` was updated but nothing else. After I cleared the entire KV cache, things worked fine. Anyway, I'm hesitant to approve & merge myself (which will auto-deploy) in case it'll cause an issue transitioning to the production websites since I don't have access to fix those. I'd be happy to proceed if/when you're prepared to be available to manage things on the CF side...

**Comment by Aprillion** [comment]
hmm thanks for testing - I tried to make the transition work, but only tested it once in the middle of my changes and then everything was migrated and I made more changes 🤦 

I will have to deploy the old version to my test server and try the "migration" again

**Comment by ccstan99** [comment]
Ideally, if there's some way to purge the STAMP_KV cache whenever we deploy a new version to CF, that might be a safer way to start with a "clean slate."

**Comment by Aprillion** [comment]
Good idea, there will be a button `Clean cache` on https://ui.stampy.ai/questions/cache (preview: https://stampy-ui.aprillion.workers.dev/questions/cache) + I added a step to github action to send the POST request to clean cache, let's see if it works.

**Review by ccstan99 — APPROVED** [review]
Thanks so much for taking care of all of this! Wishing us luck for a smooth deployment.

**Comment by ccstan99** [comment]
GH Action failed and https://ui.stampy.ai/questions/cache doesn't seem to work. I tested it on my dev CF and it was fine. Fortunately, https://ui.stampy.ai/ and https://alignment.wiki/ still work, for now.
Screen Shot 2022-10-30 at 12 24 39 PM
Screen Shot 2022-10-30 at 12 28 51 PM

**Pull request merged**
