### PR TITLE
Update frontpage suggestions.

### PR DESCRIPTION
**Pull request by LeMurphant**
I still think ideally the title should be fetched from the page directlly and not specified here

### CODE REVIEW

**Comment by mruwnik** [comment]
agreed :/

Also, you'll have to run `npm run lint:fix`

**Comment by LeMurphant** [comment]
@mruwnik I ran the command and got an error in a file I did not modify. The error also shows up on the master branch.

`stampy-ui/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
`

**Comment by mruwnik** [comment]
huh. This is a typescript error, which is concerning. Have you updated your node modules recently? Does removing them and reinstalling work (`rm -R node_modules && npm install`)?

**Comment by LeMurphant** [comment]
Ubuntu jammy had installed npm v8.5, I manually updated to v22.8.0 and it works.

**Review by mruwnik — APPROVED** [review]

**Pull request merged**
