### PR TITLE
images for video thumbnail

### PR DESCRIPTION
**Pull request by melissasamworth**

### CODE REVIEW

**Review by mruwnik — COMMENTED** [review]
would it be possible to just merge them? Or is that a bad idea?

**Comment by LeMurphant** [comment]
@mruwnik Merge this image with what?

**Comment by bryceerobertson** [comment]
I think he means put the images together into one

**Comment by melissasamworth** [comment]
@mruwnik I stubbornly don't want to because one is SVG the other is bitmap

**Review by mruwnik — APPROVED** [review]

**Pull request merged**
