### PR TITLE
[WIP] Add tags page

### PR DESCRIPTION
**Pull request by mruwnik**
https://github.com/StampyAI/stampy-ui/issues/212

An initial version of the tags page. This will require a lot in the way of styling/design stuff, but the actual functionality is there

image

### CODE REVIEW

**Comment by ccstan99** [comment]
I'd support no icons or at most AI generated, ie.
```
ChatGPT, can you generate an emoji for each of these tags?
Certainly! Here are emojis for each of the tags you mentioned:
Definition: 📖
AGI: 🧠
Contributing: 🤝
Why Not Just: ❓🚫
Timelines: ⏰
AI takeoff: 🚀
Existential Risk: ⚠️
Government: 🏛️
Plausibility: 🤔
S-risk: 💀
Literature: 📚
Interpretability: 🔍
```

Couple tag navigation approaches as reference for discussion:
- https://lapl.overdrive.com/browse#format=audiobook
Sitemap, maybe most similar current propose but clicking goes to page with links, avoids popup dialog. Maybe more coherence flow? 
- https://huggingface.co/models?pipeline_tag=graph-ml&sort=downloads
Long list of tags which filter list on right

**Review by plexish — APPROVED** [review]
Looks good! How is it linked from the homepage? And weakly prefer AI generated emojis, can store in coda and have coda auto-generate with coda AI once we get that?

**Comment by mruwnik** [comment]
it's not linked yet. Which of course raises the question how it should be. I reckon it would be good to discuss this properly on the dev meeting :D

**Comment by mruwnik** [comment]
overhauled it: 
image

**Comment by Aprillion** [comment]
Pushing a few CSS improvements for mobile screen sizes:
iPhone 375px iPad 810px

**Review by Aprillion — APPROVED** [review]

**Pull request merged**
