### PR TITLE
Open external links on new tab

### PR DESCRIPTION
**Pull request by Aprillion**
Code cleanup & fixing #222 

image

Testable on https://stampy-ui.aprillion.workers.dev/

### CODE REVIEW

**Comment by Aprillion** [comment]
aaah, we don't use post css and Chrome only supports `-webkit-mask`, need up update 😓

**Review by mruwnik — APPROVED** [review]
Approved, because the code seems correct, and clicking on the links works.
At the same time, I'd like to note that I agree with your initial doubts, and so am disappointed at how you didn't wait for someone else to implement it, hence failed condemning it to languish in the backlog :P

**Comment by ccstan99** [comment]
Sorry to be the pain but my fault for reviving the languishing zombie. Unfortunately, it's the right thing to do from a user's expectation point of view and for metrics, although it'll open a different set of issues for editors to rethink how they structure content and links.

**Comment by Aprillion** [comment]
This is part of our code that wouldn't make a good first issue to welcome new developers, and it was deemed important by many stakeholders in our team, so I decided to implement it so the issue stops haunting us 🤷‍♂️ 

@mruwnik feel free to add a condition like `if (!localStorage.get('disableExternalLinksOpenOnNewTab'))` if you think it might be important to have that option (and we could ask to include it as a user-visible setting in the UI redesign later this year)

**Comment by ccstan99** [comment]
@Aprillion @mruwnik Just so I better understand your concerns... Is the problem nasty code maintenance? Or users overwhelmed with too many new tabs? If it's the latter, we could ask the user which they prefer ("Open in new tab or replace current one?" with an option "Remember this setting." Or does require cookies that we need to avoid?

**Comment by mruwnik** [comment]
no, it's more about changing standards. Or leaving things as default as possible. It's part of the general process of websites taking on more and more of the basic functionality of browsers, which can be helpful, but often just makes things more counter intuitive. Though this may be a matter of "get off my lawn!!"? :D

It takes away freedom in the name of temporary comfort. And breaks one of the potential user flows.

I don't think having millions of options like this would help much. That's going back to badly reimplementing the browser in JS.

**Pull request merged**
